// Loadable modules
//
// Generated by /export/home/urawat/Downloads/paraview_build/bin/vtkkwProcessXML-pv5.3
//
#ifndef __vtkSMXML_LCSIntersection_h
#define __vtkSMXML_LCSIntersection_h

#include <string.h>


// From file /export/home/urawat/Desktop/LCSIntersection/LCSIntersection.xml
static const char* const LCSIntersectionLCSIntersectionInterfaces0 =
"<ServerManagerConfiguration>\n"
"    <ProxyGroup name=\"filters\">\n"
"        <SourceProxy\n"
"                name=\"LCSIntersection\"\n"
"                class=\"vtkLCSIntersection\"\n"
"                label=\"LCSIntersection\">	<!-- name as it will appear in ParaView under \"Filters\" menu -->\n"
"\n"
"            <Documentation\n"
"                    long_help=\"Calculates number of LCS Intersections\"\n"
"                    short_help=\"Calculates LCS Intersections\">\n"
"                Extracts ridge lines on uniform grids.\n"
"            </Documentation>\n"
"\n"
"            <InputProperty\n"
"                    name=\"Input\"\n"
"                    command=\"AddInputConnection\"\n"
"                    clean_command=\"RemoveAllInputs\">\n"
"                <ProxyGroupDomain name=\"groups\">\n"
"                    <Group name=\"sources\"/> <!-- the input might come either from a reader-->\n"
"                    <Group name=\"filters\"/> <!-- ... or from another filter -->\n"
"                </ProxyGroupDomain>\n"
"                <DataTypeDomain name=\"input_type\">\n"
"                    <DataType value=\"vtkPolyData\"/> <!-- We require that the data has type vtkDataSet; might as well be more specific (e.g., vtkRectilinearGrid) -->\n"
"                </DataTypeDomain>\n"
"            </InputProperty>\n"
"\n"
"            <IntVectorProperty\n"
"                    name=\"Number of cells\"\n"
"                    command=\"SetcellsNumber\"\n"
"                    number_of_elements=\"3\"\n"
"                    default_values=\"200 100 1\">\n"
"                <Documentation>\n"
"                    Number of cells in each direction.\n"
"                </Documentation>\n"
"            </IntVectorProperty>\n"
"\n"
"        </SourceProxy>\n"
"    </ProxyGroup>\n"
"</ServerManagerConfiguration>\n"
"\n";
// Get single string
char* LCSIntersectionLCSIntersectionInterfaces()
{
  size_t len = ( 0
    + strlen(LCSIntersectionLCSIntersectionInterfaces0) );
  char* res = new char[ len + 1];
  res[0] = 0;
  strcat(res, LCSIntersectionLCSIntersectionInterfaces0);
  return res;
}



#endif
